version: '3.8'

services:
  main-web-app:
    container_name: main-web-app
    build:
      context: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  stirling-pdf:
    container_name: stirling-pdf
    image: frooodle/s-pdf:latest
    ports:
      - '8081:8080'
    volumes:
      - /location/of/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /location/of/extraConfigs:/configs
      # - /location/of/customFiles:/customFiles/
      # - /location/of/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false

  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    ports:
      - "8082:80"
  
  resumeio-to-pdf:
    container_name: resumeio-to-pdf
    build:
      context: https://github.com/jer-0/resumeio-to-pdf.git#main
    ports:
      - "8083:8000"
    restart: unless-stopped

  caddy:
    image: caddy:2.7.6-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy:/config
      - caddy_data:/data
      - /var/www:/var/www

networks:
  default:
    name: caddy
    external: true

volumes:
  caddy_data:
    external: true
  # caddy: